sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "16.13"
script:
  - npm run cover
  - npm run coverage:check
  - npm run build
after_success:
  - npm run coverage:report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
