name: Mobx React Form
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run tests
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
