name: Mobx React Form
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run cover
      - run: npm run coverage:check
      - run: npm run build
      - run: npm run coverage:report
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
